# development:
#  adapter: mysql2
#  database:
#  username:
#  password:
#  host: localhost
#  encoding: utf8

# test:
#  database: testdb
#  adapter: mysql2
#  encoding: utf8
#  username:
#  password:
#  host: localhost

# production:
#  adapter: mysql2
#  database: Railsdb
#  username:
#  password:
#  host: localhost
#  encoding: utf8
